name: 💡 Feature Request
description: Have a new idea/feature for this project? Please suggest!
title: '💡 [FEATURE] <description>'
labels: ['enhancement']
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Description of the enhancement you propose, also include what you tried and what worked.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Screenshots if applicable
    validations:
      required: false
  - type: text
    id: guide
    attributes:
      label: Check out the getting started guide here: Check out the getting started guide here:
https://github.com/Rutuj-Runwal/RR-Adblocker/blob/main/documentation/Getting%20Started/Getting_Started.md
